// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcagpifccqpzwceyztee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjYWdwaWZjY3FwendjZXl6dGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzgwNzEsImV4cCI6MjA3MTI1NDA3MX0.GBG7AiFKH3SlWK-A-Ly26mpbo352IOzG4HmZWLPdZDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});